package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 14:09:39 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AttachmentsRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AttachmentsRVOImpl() {
    }    
}
