package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 21 12:24:36 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TicketingToolTransVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TicketingToolTransVOImpl() {
    }
//    public String getNew() {
//           return "New";
//
//      }
    public String getLow() {
           return "Low";
    }
    
}
