package model.common;

import java.util.Date;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 05 12:00:26 IST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void updateAttachment(String ticId, String fileName, String contentType,
                          BlobDomain blob);

    void searchSubmit(Date closeddate);

    void onSearch();

    void onPopupComments(String ticId, String comments);

    void onAdminProjectName(String projectName, Date startdate, Date enddate);

    String generateNumber();

    void forDelete(String AttachId, String ticId);

    void emptyAttachments();

    void checkProjectName();

    void addUser();

    String CreateTicketingTool(Date closeddate, String assignedTo);

    void CreateAttachment();
}
