package model.client;

import java.util.Date;

import model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 05 12:00:26 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void updateAttachment(String ticId, String fileName,
                                 String contentType, BlobDomain blob) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateAttachment",new String [] {"java.lang.String","java.lang.String","java.lang.String","oracle.jbo.domain.BlobDomain"},new Object[] {ticId, fileName, contentType, blob});
        return;
    }

    public void searchSubmit(Date closeddate) {
        Object _ret =
            this.riInvokeExportedMethod(this,"searchSubmit",new String [] {"java.util.Date"},new Object[] {closeddate});
        return;
    }

    public void onSearch() {
        Object _ret = this.riInvokeExportedMethod(this,"onSearch",null,null);
        return;
    }

    public void onPopupComments(String ticId, String comments) {
        Object _ret =
            this.riInvokeExportedMethod(this,"onPopupComments",new String [] {"java.lang.String","java.lang.String"},new Object[] {ticId, comments});
        return;
    }

    public void onAdminProjectName(String projectName, Date startdate,
                                   Date enddate) {
        Object _ret =
            this.riInvokeExportedMethod(this,"onAdminProjectName",new String [] {"java.lang.String","java.util.Date","java.util.Date"},new Object[] {projectName, startdate, enddate});
        return;
    }

    public String generateNumber() {
        Object _ret = this.riInvokeExportedMethod(this,"generateNumber",null,null);
        return (String)_ret;
    }

    public void forDelete(String AttachId, String ticId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"forDelete",new String [] {"java.lang.String","java.lang.String"},new Object[] {AttachId, ticId});
        return;
    }

    public void emptyAttachments() {
        Object _ret =
            this.riInvokeExportedMethod(this,"emptyAttachments",null,null);
        return;
    }

    public void checkProjectName() {
        Object _ret =
            this.riInvokeExportedMethod(this,"checkProjectName",null,null);
        return;
    }

    public void addUser() {
        Object _ret = this.riInvokeExportedMethod(this,"addUser",null,null);
        return;
    }

    public String CreateTicketingTool(Date closeddate, String assignedTo) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CreateTicketingTool",new String [] {"java.util.Date","java.lang.String"},new Object[] {closeddate, assignedTo});
        return (String)_ret;
    }

    public void CreateAttachment() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CreateAttachment",null,null);
        return;
    }
}
